let mavzular = [
	{ 
		id : 1,
		mavzuRaqam : 1.1 ,
		nomi : "Gul",
		bet: 8 ,
	},
	{
		id : 2 ,
		mavzuRaqam : 1.2 ,
		nomi : "Gulli O'simliklarning Ko'payishi" ,
		bet: 8 ,
	},
	{	
		id : 3 ,
		mavzuRaqam :1.3  ,
		nomi :"Urug'larning unib chiqishi" ,
		bet: 8 ,
	},
	{  
		id : 4 ,
		mavzuRaqam : 2.1 ,
		nomi : "Yashash muhitiga moslanish",
		bet: 8 ,
	},
	{	
		id : 5 ,
		mavzuRaqam : 2.2 ,
		nomi : "Gulli o'shimliklarning moslanishlari",
		bet: 8 ,
	},
	{	id : 6 ,
		mavzuRaqam : 2.3 ,
		nomi : "Yirtqichlar va ularning o'ljalaridagi moslanishlar" ,
		bet: 8 ,
	},
	{	id : 7 ,
		mavzuRaqam : 3.1  ,
		nomi : "Qattiq, suyuq va gazsimon moddalarning tuzilishi" ,
		bet: 8 ,
	},
	{	id : 8,
		mavzuRaqam :3.2  ,
		nomi : "" ,
		bet:  9,
	},
]